Feature/p20 1 usuário visualiza todas tarefas
tribos-dev/produdoro-t2022-01-s01 pull request #7
Opened 2022-06-26 14:08 UTC by Danilo1dev

Solicito pull request da feature P20-1

2022-06-26 14:58 UTC, vinireis requested changes
Você conseguiu testar sua atividade?
Acredito que ela não esteja funcionando!

2022-06-26 14:58 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/api/TarefaAPI.java
> +		@GetMapping ("/{idTarefa}/tarefa")
mudaria url para tarefas

2022-06-26 14:58 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/api/TarefaDTO.java
>  }
Não entendi esse arquivo?

2022-06-26 14:58 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/repository/TarefaRepository.java
> +	List<Tarefa> buscaTarefaPorIdUsuario(@Valid UUID IdUsuario);
mudaria o nome o método para buscarTarefasPorIdUsuario. Ficaria mais semântico.

2022-06-26 14:58 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/service/TarefaSpringMongoDBService.java
> +@Setter
Por que esses caras aqui?

2022-06-26 14:58 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/infra/TarefaMongoDBSpringRepository.java
> +	Optional<Tarefa> findByIdTarefa(UUID idTarefa);
Por que esse cara?

2022-06-26 14:58 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/infra/TarefaMongoDBSpringRepository.java
> +	void delete(Tarefa tarefaPorId);
Por que esse cara?

2022-06-26 15:58 UTC, Danilo1dev commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/api/TarefaDTO.java
>  }
O correto seria esse aqui. Mais fica dando conflito e eu não conseguir achar. Vou dar uma revisada novamente.
>> return listaTarefa.stream().**_ map(TarefaDTO::new)_**.collect(Collectors.toList());
por isso add o null;

2022-07-09 15:37 UTC, fesacaba approved these changes
Validei seu codigo, dois pontos que são importantes comentar. 1 - Anotação @Valid no objeto do repository, o ideal seria que fosse validado ja na entrada da aplicação, no Controller. 2 - Faltou uma anotação @Override na implementação de um metodo que estava na interface. Fiz o merge com a Dev resolvendo os conflitos, o ideial é sempre dar um "git pull" antes de abrir o PR, para verificar se não tem alguma atualização na branch remota.

2022-07-09 15:37 UTC, merged